//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketDemo.RequestHisData {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://RequestHisData/", ConfigurationName="RequestHisData.RequestHisDataSoap")]
    public interface RequestHisDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://RequestHisData/reqHisBaseData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reqHisBaseData(string[] tagNames, System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://RequestHisData/reqAccountData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reqAccountData(string[] tagNames, System.DateTime beginTime, System.DateTime endTime, int anaFlag, int accountType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequestHisDataSoapChannel : SocketDemo.RequestHisData.RequestHisDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestHisDataSoapClient : System.ServiceModel.ClientBase<SocketDemo.RequestHisData.RequestHisDataSoap>, SocketDemo.RequestHisData.RequestHisDataSoap {
        
        public RequestHisDataSoapClient() {
        }
        
        public RequestHisDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestHisDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestHisDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestHisDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet reqHisBaseData(string[] tagNames, System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.reqHisBaseData(tagNames, beginTime, endTime);
        }
        
        public System.Data.DataSet reqAccountData(string[] tagNames, System.DateTime beginTime, System.DateTime endTime, int anaFlag, int accountType) {
            return base.Channel.reqAccountData(tagNames, beginTime, endTime, anaFlag, accountType);
        }
    }
}
