//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketDemo.SystemInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventStruct", Namespace="http://SystemInfo/")]
    [System.SerializableAttribute()]
    public partial class EventStruct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string appName {
            get {
                return this.appNameField;
            }
            set {
                if ((object.ReferenceEquals(this.appNameField, value) != true)) {
                    this.appNameField = value;
                    this.RaisePropertyChanged("appName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://SystemInfo/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SystemInfo/", ConfigurationName="SystemInfo.SystemInfoSoap")]
    public interface SystemInfoSoap {
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 eventstructs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/writeEventEx", ReplyAction="*")]
        SocketDemo.SystemInfo.writeEventExResponse writeEventEx(SocketDemo.SystemInfo.writeEventExRequest request);
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 eventstruct 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/writeEvent", ReplyAction="*")]
        SocketDemo.SystemInfo.writeEventResponse writeEvent(SocketDemo.SystemInfo.writeEventRequest request);
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 appName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/readEvent", ReplyAction="*")]
        SocketDemo.SystemInfo.readEventResponse readEvent(SocketDemo.SystemInfo.readEventRequest request);
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 appName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/readEventString", ReplyAction="*")]
        SocketDemo.SystemInfo.readEventStringResponse readEventString(SocketDemo.SystemInfo.readEventStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/refresh", ReplyAction="*")]
        int refresh();
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 getAppNameResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/getAppName", ReplyAction="*")]
        SocketDemo.SystemInfo.getAppNameResponse getAppName(SocketDemo.SystemInfo.getAppNameRequest request);
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 appName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/getEventCount", ReplyAction="*")]
        SocketDemo.SystemInfo.getEventCountResponse getEventCount(SocketDemo.SystemInfo.getEventCountRequest request);
        
        // CODEGEN: 命名空间 http://SystemInfo/ 的元素名称 appName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SystemInfo/clearAppInfo", ReplyAction="*")]
        SocketDemo.SystemInfo.clearAppInfoResponse clearAppInfo(SocketDemo.SystemInfo.clearAppInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class writeEventExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="writeEventEx", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.writeEventExRequestBody Body;
        
        public writeEventExRequest() {
        }
        
        public writeEventExRequest(SocketDemo.SystemInfo.writeEventExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class writeEventExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.SystemInfo.EventStruct[] eventstructs;
        
        public writeEventExRequestBody() {
        }
        
        public writeEventExRequestBody(SocketDemo.SystemInfo.EventStruct[] eventstructs) {
            this.eventstructs = eventstructs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class writeEventExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="writeEventExResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.writeEventExResponseBody Body;
        
        public writeEventExResponse() {
        }
        
        public writeEventExResponse(SocketDemo.SystemInfo.writeEventExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class writeEventExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int writeEventExResult;
        
        public writeEventExResponseBody() {
        }
        
        public writeEventExResponseBody(int writeEventExResult) {
            this.writeEventExResult = writeEventExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class writeEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="writeEvent", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.writeEventRequestBody Body;
        
        public writeEventRequest() {
        }
        
        public writeEventRequest(SocketDemo.SystemInfo.writeEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class writeEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.SystemInfo.EventStruct eventstruct;
        
        public writeEventRequestBody() {
        }
        
        public writeEventRequestBody(SocketDemo.SystemInfo.EventStruct eventstruct) {
            this.eventstruct = eventstruct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class writeEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="writeEventResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.writeEventResponseBody Body;
        
        public writeEventResponse() {
        }
        
        public writeEventResponse(SocketDemo.SystemInfo.writeEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class writeEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int writeEventResult;
        
        public writeEventResponseBody() {
        }
        
        public writeEventResponseBody(int writeEventResult) {
            this.writeEventResult = writeEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readEvent", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.readEventRequestBody Body;
        
        public readEventRequest() {
        }
        
        public readEventRequest(SocketDemo.SystemInfo.readEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class readEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public readEventRequestBody() {
        }
        
        public readEventRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readEventResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.readEventResponseBody Body;
        
        public readEventResponse() {
        }
        
        public readEventResponse(SocketDemo.SystemInfo.readEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class readEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.SystemInfo.ArrayOfString readEventResult;
        
        public readEventResponseBody() {
        }
        
        public readEventResponseBody(SocketDemo.SystemInfo.ArrayOfString readEventResult) {
            this.readEventResult = readEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readEventStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readEventString", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.readEventStringRequestBody Body;
        
        public readEventStringRequest() {
        }
        
        public readEventStringRequest(SocketDemo.SystemInfo.readEventStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class readEventStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public readEventStringRequestBody() {
        }
        
        public readEventStringRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readEventStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readEventStringResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.readEventStringResponseBody Body;
        
        public readEventStringResponse() {
        }
        
        public readEventStringResponse(SocketDemo.SystemInfo.readEventStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class readEventStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string readEventStringResult;
        
        public readEventStringResponseBody() {
        }
        
        public readEventStringResponseBody(string readEventStringResult) {
            this.readEventStringResult = readEventStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAppNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAppName", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.getAppNameRequestBody Body;
        
        public getAppNameRequest() {
        }
        
        public getAppNameRequest(SocketDemo.SystemInfo.getAppNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAppNameRequestBody {
        
        public getAppNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAppNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAppNameResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.getAppNameResponseBody Body;
        
        public getAppNameResponse() {
        }
        
        public getAppNameResponse(SocketDemo.SystemInfo.getAppNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class getAppNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.SystemInfo.ArrayOfString getAppNameResult;
        
        public getAppNameResponseBody() {
        }
        
        public getAppNameResponseBody(SocketDemo.SystemInfo.ArrayOfString getAppNameResult) {
            this.getAppNameResult = getAppNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEventCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEventCount", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.getEventCountRequestBody Body;
        
        public getEventCountRequest() {
        }
        
        public getEventCountRequest(SocketDemo.SystemInfo.getEventCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class getEventCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public getEventCountRequestBody() {
        }
        
        public getEventCountRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEventCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEventCountResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.getEventCountResponseBody Body;
        
        public getEventCountResponse() {
        }
        
        public getEventCountResponse(SocketDemo.SystemInfo.getEventCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class getEventCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getEventCountResult;
        
        public getEventCountResponseBody() {
        }
        
        public getEventCountResponseBody(int getEventCountResult) {
            this.getEventCountResult = getEventCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clearAppInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clearAppInfo", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.clearAppInfoRequestBody Body;
        
        public clearAppInfoRequest() {
        }
        
        public clearAppInfoRequest(SocketDemo.SystemInfo.clearAppInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class clearAppInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public clearAppInfoRequestBody() {
        }
        
        public clearAppInfoRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clearAppInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clearAppInfoResponse", Namespace="http://SystemInfo/", Order=0)]
        public SocketDemo.SystemInfo.clearAppInfoResponseBody Body;
        
        public clearAppInfoResponse() {
        }
        
        public clearAppInfoResponse(SocketDemo.SystemInfo.clearAppInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SystemInfo/")]
    public partial class clearAppInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int clearAppInfoResult;
        
        public clearAppInfoResponseBody() {
        }
        
        public clearAppInfoResponseBody(int clearAppInfoResult) {
            this.clearAppInfoResult = clearAppInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SystemInfoSoapChannel : SocketDemo.SystemInfo.SystemInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemInfoSoapClient : System.ServiceModel.ClientBase<SocketDemo.SystemInfo.SystemInfoSoap>, SocketDemo.SystemInfo.SystemInfoSoap {
        
        public SystemInfoSoapClient() {
        }
        
        public SystemInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.writeEventExResponse SocketDemo.SystemInfo.SystemInfoSoap.writeEventEx(SocketDemo.SystemInfo.writeEventExRequest request) {
            return base.Channel.writeEventEx(request);
        }
        
        public int writeEventEx(SocketDemo.SystemInfo.EventStruct[] eventstructs) {
            SocketDemo.SystemInfo.writeEventExRequest inValue = new SocketDemo.SystemInfo.writeEventExRequest();
            inValue.Body = new SocketDemo.SystemInfo.writeEventExRequestBody();
            inValue.Body.eventstructs = eventstructs;
            SocketDemo.SystemInfo.writeEventExResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).writeEventEx(inValue);
            return retVal.Body.writeEventExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.writeEventResponse SocketDemo.SystemInfo.SystemInfoSoap.writeEvent(SocketDemo.SystemInfo.writeEventRequest request) {
            return base.Channel.writeEvent(request);
        }
        
        public int writeEvent(SocketDemo.SystemInfo.EventStruct eventstruct) {
            SocketDemo.SystemInfo.writeEventRequest inValue = new SocketDemo.SystemInfo.writeEventRequest();
            inValue.Body = new SocketDemo.SystemInfo.writeEventRequestBody();
            inValue.Body.eventstruct = eventstruct;
            SocketDemo.SystemInfo.writeEventResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).writeEvent(inValue);
            return retVal.Body.writeEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.readEventResponse SocketDemo.SystemInfo.SystemInfoSoap.readEvent(SocketDemo.SystemInfo.readEventRequest request) {
            return base.Channel.readEvent(request);
        }
        
        public SocketDemo.SystemInfo.ArrayOfString readEvent(string appName) {
            SocketDemo.SystemInfo.readEventRequest inValue = new SocketDemo.SystemInfo.readEventRequest();
            inValue.Body = new SocketDemo.SystemInfo.readEventRequestBody();
            inValue.Body.appName = appName;
            SocketDemo.SystemInfo.readEventResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).readEvent(inValue);
            return retVal.Body.readEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.readEventStringResponse SocketDemo.SystemInfo.SystemInfoSoap.readEventString(SocketDemo.SystemInfo.readEventStringRequest request) {
            return base.Channel.readEventString(request);
        }
        
        public string readEventString(string appName) {
            SocketDemo.SystemInfo.readEventStringRequest inValue = new SocketDemo.SystemInfo.readEventStringRequest();
            inValue.Body = new SocketDemo.SystemInfo.readEventStringRequestBody();
            inValue.Body.appName = appName;
            SocketDemo.SystemInfo.readEventStringResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).readEventString(inValue);
            return retVal.Body.readEventStringResult;
        }
        
        public int refresh() {
            return base.Channel.refresh();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.getAppNameResponse SocketDemo.SystemInfo.SystemInfoSoap.getAppName(SocketDemo.SystemInfo.getAppNameRequest request) {
            return base.Channel.getAppName(request);
        }
        
        public SocketDemo.SystemInfo.ArrayOfString getAppName() {
            SocketDemo.SystemInfo.getAppNameRequest inValue = new SocketDemo.SystemInfo.getAppNameRequest();
            inValue.Body = new SocketDemo.SystemInfo.getAppNameRequestBody();
            SocketDemo.SystemInfo.getAppNameResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).getAppName(inValue);
            return retVal.Body.getAppNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.getEventCountResponse SocketDemo.SystemInfo.SystemInfoSoap.getEventCount(SocketDemo.SystemInfo.getEventCountRequest request) {
            return base.Channel.getEventCount(request);
        }
        
        public int getEventCount(string appName) {
            SocketDemo.SystemInfo.getEventCountRequest inValue = new SocketDemo.SystemInfo.getEventCountRequest();
            inValue.Body = new SocketDemo.SystemInfo.getEventCountRequestBody();
            inValue.Body.appName = appName;
            SocketDemo.SystemInfo.getEventCountResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).getEventCount(inValue);
            return retVal.Body.getEventCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.SystemInfo.clearAppInfoResponse SocketDemo.SystemInfo.SystemInfoSoap.clearAppInfo(SocketDemo.SystemInfo.clearAppInfoRequest request) {
            return base.Channel.clearAppInfo(request);
        }
        
        public int clearAppInfo(string appName) {
            SocketDemo.SystemInfo.clearAppInfoRequest inValue = new SocketDemo.SystemInfo.clearAppInfoRequest();
            inValue.Body = new SocketDemo.SystemInfo.clearAppInfoRequestBody();
            inValue.Body.appName = appName;
            SocketDemo.SystemInfo.clearAppInfoResponse retVal = ((SocketDemo.SystemInfo.SystemInfoSoap)(this)).clearAppInfo(inValue);
            return retVal.Body.clearAppInfoResult;
        }
    }
}
