//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketDemo.CDataCenter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://CDataCenter/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUpDataValue", Namespace="http://CDataCenter/", ItemName="upDataValue")]
    [System.SerializableAttribute()]
    public class ArrayOfUpDataValue : System.Collections.Generic.List<SocketDemo.CDataCenter.upDataValue> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="upDataValue", Namespace="http://CDataCenter/")]
    [System.SerializableAttribute()]
    public partial class upDataValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagNameField;
        
        private int tagIDField;
        
        private float valField;
        
        private int dataValidateField;
        
        private System.DateTime deviceTimeField;
        
        private int valStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tagName {
            get {
                return this.tagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tagNameField, value) != true)) {
                    this.tagNameField = value;
                    this.RaisePropertyChanged("tagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int tagID {
            get {
                return this.tagIDField;
            }
            set {
                if ((this.tagIDField.Equals(value) != true)) {
                    this.tagIDField = value;
                    this.RaisePropertyChanged("tagID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float val {
            get {
                return this.valField;
            }
            set {
                if ((this.valField.Equals(value) != true)) {
                    this.valField = value;
                    this.RaisePropertyChanged("val");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int dataValidate {
            get {
                return this.dataValidateField;
            }
            set {
                if ((this.dataValidateField.Equals(value) != true)) {
                    this.dataValidateField = value;
                    this.RaisePropertyChanged("dataValidate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime deviceTime {
            get {
                return this.deviceTimeField;
            }
            set {
                if ((this.deviceTimeField.Equals(value) != true)) {
                    this.deviceTimeField = value;
                    this.RaisePropertyChanged("deviceTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int valState {
            get {
                return this.valStateField;
            }
            set {
                if ((this.valStateField.Equals(value) != true)) {
                    this.valStateField = value;
                    this.RaisePropertyChanged("valState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUpWriteStruct", Namespace="http://CDataCenter/", ItemName="upWriteStruct")]
    [System.SerializableAttribute()]
    public class ArrayOfUpWriteStruct : System.Collections.Generic.List<SocketDemo.CDataCenter.upWriteStruct> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="upWriteStruct", Namespace="http://CDataCenter/")]
    [System.SerializableAttribute()]
    public partial class upWriteStruct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valField;
        
        private int dataValidateField;
        
        private System.DateTime deviceTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tagName {
            get {
                return this.tagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tagNameField, value) != true)) {
                    this.tagNameField = value;
                    this.RaisePropertyChanged("tagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string val {
            get {
                return this.valField;
            }
            set {
                if ((object.ReferenceEquals(this.valField, value) != true)) {
                    this.valField = value;
                    this.RaisePropertyChanged("val");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int dataValidate {
            get {
                return this.dataValidateField;
            }
            set {
                if ((this.dataValidateField.Equals(value) != true)) {
                    this.dataValidateField = value;
                    this.RaisePropertyChanged("dataValidate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime deviceTime {
            get {
                return this.deviceTimeField;
            }
            set {
                if ((this.deviceTimeField.Equals(value) != true)) {
                    this.deviceTimeField = value;
                    this.RaisePropertyChanged("deviceTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDownDataValue", Namespace="http://CDataCenter/", ItemName="downDataValue")]
    [System.SerializableAttribute()]
    public class ArrayOfDownDataValue : System.Collections.Generic.List<SocketDemo.CDataCenter.downDataValue> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="downDataValue", Namespace="http://CDataCenter/")]
    [System.SerializableAttribute()]
    public partial class downDataValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string driverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataNoField;
        
        private float valField;
        
        private int dataValidateField;
        
        private System.DateTime deviceTimeField;
        
        private int valStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string driverName {
            get {
                return this.driverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.driverNameField, value) != true)) {
                    this.driverNameField = value;
                    this.RaisePropertyChanged("driverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataNo {
            get {
                return this.dataNoField;
            }
            set {
                if ((object.ReferenceEquals(this.dataNoField, value) != true)) {
                    this.dataNoField = value;
                    this.RaisePropertyChanged("dataNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float val {
            get {
                return this.valField;
            }
            set {
                if ((this.valField.Equals(value) != true)) {
                    this.valField = value;
                    this.RaisePropertyChanged("val");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int dataValidate {
            get {
                return this.dataValidateField;
            }
            set {
                if ((this.dataValidateField.Equals(value) != true)) {
                    this.dataValidateField = value;
                    this.RaisePropertyChanged("dataValidate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime deviceTime {
            get {
                return this.deviceTimeField;
            }
            set {
                if ((this.deviceTimeField.Equals(value) != true)) {
                    this.deviceTimeField = value;
                    this.RaisePropertyChanged("deviceTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int valState {
            get {
                return this.valStateField;
            }
            set {
                if ((this.valStateField.Equals(value) != true)) {
                    this.valStateField = value;
                    this.RaisePropertyChanged("valState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CDataCenter/", ConfigurationName="CDataCenter.CDataCenterSoap")]
    public interface CDataCenterSoap {
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 tagName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/UpReadValue", ReplyAction="*")]
        SocketDemo.CDataCenter.UpReadValueResponse UpReadValue(SocketDemo.CDataCenter.UpReadValueRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 tagNames 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/OnlineDataReadValueString", ReplyAction="*")]
        SocketDemo.CDataCenter.OnlineDataReadValueStringResponse OnlineDataReadValueString(SocketDemo.CDataCenter.OnlineDataReadValueStringRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 tagName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/OnlineDataReadValue", ReplyAction="*")]
        SocketDemo.CDataCenter.OnlineDataReadValueResponse OnlineDataReadValue(SocketDemo.CDataCenter.OnlineDataReadValueRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 upwritestruct 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/UpWriteValue", ReplyAction="*")]
        SocketDemo.CDataCenter.UpWriteValueResponse UpWriteValue(SocketDemo.CDataCenter.UpWriteValueRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 driverNames 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/DownReadValueString", ReplyAction="*")]
        SocketDemo.CDataCenter.DownReadValueStringResponse DownReadValueString(SocketDemo.CDataCenter.DownReadValueStringRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 driverName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/DownReadValue", ReplyAction="*")]
        SocketDemo.CDataCenter.DownReadValueResponse DownReadValue(SocketDemo.CDataCenter.DownReadValueRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 downdatavalues 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/DownWriteValueString", ReplyAction="*")]
        SocketDemo.CDataCenter.DownWriteValueStringResponse DownWriteValueString(SocketDemo.CDataCenter.DownWriteValueStringRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 downdatavalue 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/DownWriteValue", ReplyAction="*")]
        SocketDemo.CDataCenter.DownWriteValueResponse DownWriteValue(SocketDemo.CDataCenter.DownWriteValueRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 tagNames 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/AddDevice", ReplyAction="*")]
        SocketDemo.CDataCenter.AddDeviceResponse AddDevice(SocketDemo.CDataCenter.AddDeviceRequest request);
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 tagName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/RemoveDevice", ReplyAction="*")]
        SocketDemo.CDataCenter.RemoveDeviceResponse RemoveDevice(SocketDemo.CDataCenter.RemoveDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/Refresh", ReplyAction="*")]
        bool Refresh();
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 DeviceName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/DownGetDeviceInfo", ReplyAction="*")]
        SocketDemo.CDataCenter.DownGetDeviceInfoResponse DownGetDeviceInfo(SocketDemo.CDataCenter.DownGetDeviceInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/testdownwritevaluestring", ReplyAction="*")]
        int testdownwritevaluestring();
        
        // CODEGEN: 命名空间 http://CDataCenter/ 的元素名称 testupreadvalueResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CDataCenter/testupreadvalue", ReplyAction="*")]
        SocketDemo.CDataCenter.testupreadvalueResponse testupreadvalue(SocketDemo.CDataCenter.testupreadvalueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpReadValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpReadValue", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.UpReadValueRequestBody Body;
        
        public UpReadValueRequest() {
        }
        
        public UpReadValueRequest(SocketDemo.CDataCenter.UpReadValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class UpReadValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfString tagName;
        
        public UpReadValueRequestBody() {
        }
        
        public UpReadValueRequestBody(SocketDemo.CDataCenter.ArrayOfString tagName) {
            this.tagName = tagName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpReadValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpReadValueResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.UpReadValueResponseBody Body;
        
        public UpReadValueResponse() {
        }
        
        public UpReadValueResponse(SocketDemo.CDataCenter.UpReadValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class UpReadValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfUpDataValue UpReadValueResult;
        
        public UpReadValueResponseBody() {
        }
        
        public UpReadValueResponseBody(SocketDemo.CDataCenter.ArrayOfUpDataValue UpReadValueResult) {
            this.UpReadValueResult = UpReadValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OnlineDataReadValueStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OnlineDataReadValueString", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.OnlineDataReadValueStringRequestBody Body;
        
        public OnlineDataReadValueStringRequest() {
        }
        
        public OnlineDataReadValueStringRequest(SocketDemo.CDataCenter.OnlineDataReadValueStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class OnlineDataReadValueStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tagNames;
        
        public OnlineDataReadValueStringRequestBody() {
        }
        
        public OnlineDataReadValueStringRequestBody(string tagNames) {
            this.tagNames = tagNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OnlineDataReadValueStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OnlineDataReadValueStringResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.OnlineDataReadValueStringResponseBody Body;
        
        public OnlineDataReadValueStringResponse() {
        }
        
        public OnlineDataReadValueStringResponse(SocketDemo.CDataCenter.OnlineDataReadValueStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class OnlineDataReadValueStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OnlineDataReadValueStringResult;
        
        public OnlineDataReadValueStringResponseBody() {
        }
        
        public OnlineDataReadValueStringResponseBody(string OnlineDataReadValueStringResult) {
            this.OnlineDataReadValueStringResult = OnlineDataReadValueStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OnlineDataReadValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OnlineDataReadValue", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.OnlineDataReadValueRequestBody Body;
        
        public OnlineDataReadValueRequest() {
        }
        
        public OnlineDataReadValueRequest(SocketDemo.CDataCenter.OnlineDataReadValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class OnlineDataReadValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfString tagName;
        
        public OnlineDataReadValueRequestBody() {
        }
        
        public OnlineDataReadValueRequestBody(SocketDemo.CDataCenter.ArrayOfString tagName) {
            this.tagName = tagName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OnlineDataReadValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OnlineDataReadValueResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.OnlineDataReadValueResponseBody Body;
        
        public OnlineDataReadValueResponse() {
        }
        
        public OnlineDataReadValueResponse(SocketDemo.CDataCenter.OnlineDataReadValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class OnlineDataReadValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfUpDataValue OnlineDataReadValueResult;
        
        public OnlineDataReadValueResponseBody() {
        }
        
        public OnlineDataReadValueResponseBody(SocketDemo.CDataCenter.ArrayOfUpDataValue OnlineDataReadValueResult) {
            this.OnlineDataReadValueResult = OnlineDataReadValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpWriteValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpWriteValue", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.UpWriteValueRequestBody Body;
        
        public UpWriteValueRequest() {
        }
        
        public UpWriteValueRequest(SocketDemo.CDataCenter.UpWriteValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class UpWriteValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfUpWriteStruct upwritestruct;
        
        public UpWriteValueRequestBody() {
        }
        
        public UpWriteValueRequestBody(SocketDemo.CDataCenter.ArrayOfUpWriteStruct upwritestruct) {
            this.upwritestruct = upwritestruct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpWriteValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpWriteValueResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.UpWriteValueResponseBody Body;
        
        public UpWriteValueResponse() {
        }
        
        public UpWriteValueResponse(SocketDemo.CDataCenter.UpWriteValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class UpWriteValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpWriteValueResult;
        
        public UpWriteValueResponseBody() {
        }
        
        public UpWriteValueResponseBody(int UpWriteValueResult) {
            this.UpWriteValueResult = UpWriteValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownReadValueStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownReadValueString", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownReadValueStringRequestBody Body;
        
        public DownReadValueStringRequest() {
        }
        
        public DownReadValueStringRequest(SocketDemo.CDataCenter.DownReadValueStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownReadValueStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string driverNames;
        
        public DownReadValueStringRequestBody() {
        }
        
        public DownReadValueStringRequestBody(string driverNames) {
            this.driverNames = driverNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownReadValueStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownReadValueStringResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownReadValueStringResponseBody Body;
        
        public DownReadValueStringResponse() {
        }
        
        public DownReadValueStringResponse(SocketDemo.CDataCenter.DownReadValueStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownReadValueStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownReadValueStringResult;
        
        public DownReadValueStringResponseBody() {
        }
        
        public DownReadValueStringResponseBody(string DownReadValueStringResult) {
            this.DownReadValueStringResult = DownReadValueStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownReadValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownReadValue", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownReadValueRequestBody Body;
        
        public DownReadValueRequest() {
        }
        
        public DownReadValueRequest(SocketDemo.CDataCenter.DownReadValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownReadValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfString driverName;
        
        public DownReadValueRequestBody() {
        }
        
        public DownReadValueRequestBody(SocketDemo.CDataCenter.ArrayOfString driverName) {
            this.driverName = driverName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownReadValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownReadValueResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownReadValueResponseBody Body;
        
        public DownReadValueResponse() {
        }
        
        public DownReadValueResponse(SocketDemo.CDataCenter.DownReadValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownReadValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfDownDataValue DownReadValueResult;
        
        public DownReadValueResponseBody() {
        }
        
        public DownReadValueResponseBody(SocketDemo.CDataCenter.ArrayOfDownDataValue DownReadValueResult) {
            this.DownReadValueResult = DownReadValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownWriteValueStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownWriteValueString", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownWriteValueStringRequestBody Body;
        
        public DownWriteValueStringRequest() {
        }
        
        public DownWriteValueStringRequest(SocketDemo.CDataCenter.DownWriteValueStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownWriteValueStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string downdatavalues;
        
        public DownWriteValueStringRequestBody() {
        }
        
        public DownWriteValueStringRequestBody(string downdatavalues) {
            this.downdatavalues = downdatavalues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownWriteValueStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownWriteValueStringResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownWriteValueStringResponseBody Body;
        
        public DownWriteValueStringResponse() {
        }
        
        public DownWriteValueStringResponse(SocketDemo.CDataCenter.DownWriteValueStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownWriteValueStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownWriteValueStringResult;
        
        public DownWriteValueStringResponseBody() {
        }
        
        public DownWriteValueStringResponseBody(int DownWriteValueStringResult) {
            this.DownWriteValueStringResult = DownWriteValueStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownWriteValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownWriteValue", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownWriteValueRequestBody Body;
        
        public DownWriteValueRequest() {
        }
        
        public DownWriteValueRequest(SocketDemo.CDataCenter.DownWriteValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownWriteValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfDownDataValue downdatavalue;
        
        public DownWriteValueRequestBody() {
        }
        
        public DownWriteValueRequestBody(SocketDemo.CDataCenter.ArrayOfDownDataValue downdatavalue) {
            this.downdatavalue = downdatavalue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownWriteValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownWriteValueResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownWriteValueResponseBody Body;
        
        public DownWriteValueResponse() {
        }
        
        public DownWriteValueResponse(SocketDemo.CDataCenter.DownWriteValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownWriteValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownWriteValueResult;
        
        public DownWriteValueResponseBody() {
        }
        
        public DownWriteValueResponseBody(int DownWriteValueResult) {
            this.DownWriteValueResult = DownWriteValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDevice", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.AddDeviceRequestBody Body;
        
        public AddDeviceRequest() {
        }
        
        public AddDeviceRequest(SocketDemo.CDataCenter.AddDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class AddDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfString tagNames;
        
        public AddDeviceRequestBody() {
        }
        
        public AddDeviceRequestBody(SocketDemo.CDataCenter.ArrayOfString tagNames) {
            this.tagNames = tagNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDeviceResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.AddDeviceResponseBody Body;
        
        public AddDeviceResponse() {
        }
        
        public AddDeviceResponse(SocketDemo.CDataCenter.AddDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class AddDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddDeviceResult;
        
        public AddDeviceResponseBody() {
        }
        
        public AddDeviceResponseBody(int AddDeviceResult) {
            this.AddDeviceResult = AddDeviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDevice", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.RemoveDeviceRequestBody Body;
        
        public RemoveDeviceRequest() {
        }
        
        public RemoveDeviceRequest(SocketDemo.CDataCenter.RemoveDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class RemoveDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfString tagName;
        
        public RemoveDeviceRequestBody() {
        }
        
        public RemoveDeviceRequestBody(SocketDemo.CDataCenter.ArrayOfString tagName) {
            this.tagName = tagName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDeviceResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.RemoveDeviceResponseBody Body;
        
        public RemoveDeviceResponse() {
        }
        
        public RemoveDeviceResponse(SocketDemo.CDataCenter.RemoveDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class RemoveDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveDeviceResult;
        
        public RemoveDeviceResponseBody() {
        }
        
        public RemoveDeviceResponseBody(int RemoveDeviceResult) {
            this.RemoveDeviceResult = RemoveDeviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownGetDeviceInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownGetDeviceInfo", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownGetDeviceInfoRequestBody Body;
        
        public DownGetDeviceInfoRequest() {
        }
        
        public DownGetDeviceInfoRequest(SocketDemo.CDataCenter.DownGetDeviceInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownGetDeviceInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeviceName;
        
        public DownGetDeviceInfoRequestBody() {
        }
        
        public DownGetDeviceInfoRequestBody(string DeviceName) {
            this.DeviceName = DeviceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownGetDeviceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownGetDeviceInfoResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.DownGetDeviceInfoResponseBody Body;
        
        public DownGetDeviceInfoResponse() {
        }
        
        public DownGetDeviceInfoResponse(SocketDemo.CDataCenter.DownGetDeviceInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class DownGetDeviceInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownGetDeviceInfoResult;
        
        public DownGetDeviceInfoResponseBody() {
        }
        
        public DownGetDeviceInfoResponseBody(string DownGetDeviceInfoResult) {
            this.DownGetDeviceInfoResult = DownGetDeviceInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testupreadvalueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testupreadvalue", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.testupreadvalueRequestBody Body;
        
        public testupreadvalueRequest() {
        }
        
        public testupreadvalueRequest(SocketDemo.CDataCenter.testupreadvalueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class testupreadvalueRequestBody {
        
        public testupreadvalueRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testupreadvalueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testupreadvalueResponse", Namespace="http://CDataCenter/", Order=0)]
        public SocketDemo.CDataCenter.testupreadvalueResponseBody Body;
        
        public testupreadvalueResponse() {
        }
        
        public testupreadvalueResponse(SocketDemo.CDataCenter.testupreadvalueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CDataCenter/")]
    public partial class testupreadvalueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SocketDemo.CDataCenter.ArrayOfUpDataValue testupreadvalueResult;
        
        public testupreadvalueResponseBody() {
        }
        
        public testupreadvalueResponseBody(SocketDemo.CDataCenter.ArrayOfUpDataValue testupreadvalueResult) {
            this.testupreadvalueResult = testupreadvalueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CDataCenterSoapChannel : SocketDemo.CDataCenter.CDataCenterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDataCenterSoapClient : System.ServiceModel.ClientBase<SocketDemo.CDataCenter.CDataCenterSoap>, SocketDemo.CDataCenter.CDataCenterSoap {
        
        public CDataCenterSoapClient() {
        }
        
        public CDataCenterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDataCenterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDataCenterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDataCenterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.UpReadValueResponse SocketDemo.CDataCenter.CDataCenterSoap.UpReadValue(SocketDemo.CDataCenter.UpReadValueRequest request) {
            return base.Channel.UpReadValue(request);
        }
        
        public SocketDemo.CDataCenter.ArrayOfUpDataValue UpReadValue(SocketDemo.CDataCenter.ArrayOfString tagName) {
            SocketDemo.CDataCenter.UpReadValueRequest inValue = new SocketDemo.CDataCenter.UpReadValueRequest();
            inValue.Body = new SocketDemo.CDataCenter.UpReadValueRequestBody();
            inValue.Body.tagName = tagName;
            SocketDemo.CDataCenter.UpReadValueResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).UpReadValue(inValue);
            return retVal.Body.UpReadValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.OnlineDataReadValueStringResponse SocketDemo.CDataCenter.CDataCenterSoap.OnlineDataReadValueString(SocketDemo.CDataCenter.OnlineDataReadValueStringRequest request) {
            return base.Channel.OnlineDataReadValueString(request);
        }
        
        public string OnlineDataReadValueString(string tagNames) {
            SocketDemo.CDataCenter.OnlineDataReadValueStringRequest inValue = new SocketDemo.CDataCenter.OnlineDataReadValueStringRequest();
            inValue.Body = new SocketDemo.CDataCenter.OnlineDataReadValueStringRequestBody();
            inValue.Body.tagNames = tagNames;
            SocketDemo.CDataCenter.OnlineDataReadValueStringResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).OnlineDataReadValueString(inValue);
            return retVal.Body.OnlineDataReadValueStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.OnlineDataReadValueResponse SocketDemo.CDataCenter.CDataCenterSoap.OnlineDataReadValue(SocketDemo.CDataCenter.OnlineDataReadValueRequest request) {
            return base.Channel.OnlineDataReadValue(request);
        }
        
        public SocketDemo.CDataCenter.ArrayOfUpDataValue OnlineDataReadValue(SocketDemo.CDataCenter.ArrayOfString tagName) {
            SocketDemo.CDataCenter.OnlineDataReadValueRequest inValue = new SocketDemo.CDataCenter.OnlineDataReadValueRequest();
            inValue.Body = new SocketDemo.CDataCenter.OnlineDataReadValueRequestBody();
            inValue.Body.tagName = tagName;
            SocketDemo.CDataCenter.OnlineDataReadValueResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).OnlineDataReadValue(inValue);
            return retVal.Body.OnlineDataReadValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.UpWriteValueResponse SocketDemo.CDataCenter.CDataCenterSoap.UpWriteValue(SocketDemo.CDataCenter.UpWriteValueRequest request) {
            return base.Channel.UpWriteValue(request);
        }
        
        public int UpWriteValue(SocketDemo.CDataCenter.ArrayOfUpWriteStruct upwritestruct) {
            SocketDemo.CDataCenter.UpWriteValueRequest inValue = new SocketDemo.CDataCenter.UpWriteValueRequest();
            inValue.Body = new SocketDemo.CDataCenter.UpWriteValueRequestBody();
            inValue.Body.upwritestruct = upwritestruct;
            SocketDemo.CDataCenter.UpWriteValueResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).UpWriteValue(inValue);
            return retVal.Body.UpWriteValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.DownReadValueStringResponse SocketDemo.CDataCenter.CDataCenterSoap.DownReadValueString(SocketDemo.CDataCenter.DownReadValueStringRequest request) {
            return base.Channel.DownReadValueString(request);
        }
        
        public string DownReadValueString(string driverNames) {
            SocketDemo.CDataCenter.DownReadValueStringRequest inValue = new SocketDemo.CDataCenter.DownReadValueStringRequest();
            inValue.Body = new SocketDemo.CDataCenter.DownReadValueStringRequestBody();
            inValue.Body.driverNames = driverNames;
            SocketDemo.CDataCenter.DownReadValueStringResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).DownReadValueString(inValue);
            return retVal.Body.DownReadValueStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.DownReadValueResponse SocketDemo.CDataCenter.CDataCenterSoap.DownReadValue(SocketDemo.CDataCenter.DownReadValueRequest request) {
            return base.Channel.DownReadValue(request);
        }
        
        public SocketDemo.CDataCenter.ArrayOfDownDataValue DownReadValue(SocketDemo.CDataCenter.ArrayOfString driverName) {
            SocketDemo.CDataCenter.DownReadValueRequest inValue = new SocketDemo.CDataCenter.DownReadValueRequest();
            inValue.Body = new SocketDemo.CDataCenter.DownReadValueRequestBody();
            inValue.Body.driverName = driverName;
            SocketDemo.CDataCenter.DownReadValueResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).DownReadValue(inValue);
            return retVal.Body.DownReadValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.DownWriteValueStringResponse SocketDemo.CDataCenter.CDataCenterSoap.DownWriteValueString(SocketDemo.CDataCenter.DownWriteValueStringRequest request) {
            return base.Channel.DownWriteValueString(request);
        }
        
        public int DownWriteValueString(string downdatavalues) {
            SocketDemo.CDataCenter.DownWriteValueStringRequest inValue = new SocketDemo.CDataCenter.DownWriteValueStringRequest();
            inValue.Body = new SocketDemo.CDataCenter.DownWriteValueStringRequestBody();
            inValue.Body.downdatavalues = downdatavalues;
            SocketDemo.CDataCenter.DownWriteValueStringResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).DownWriteValueString(inValue);
            return retVal.Body.DownWriteValueStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.DownWriteValueResponse SocketDemo.CDataCenter.CDataCenterSoap.DownWriteValue(SocketDemo.CDataCenter.DownWriteValueRequest request) {
            return base.Channel.DownWriteValue(request);
        }
        
        public int DownWriteValue(SocketDemo.CDataCenter.ArrayOfDownDataValue downdatavalue) {
            SocketDemo.CDataCenter.DownWriteValueRequest inValue = new SocketDemo.CDataCenter.DownWriteValueRequest();
            inValue.Body = new SocketDemo.CDataCenter.DownWriteValueRequestBody();
            inValue.Body.downdatavalue = downdatavalue;
            SocketDemo.CDataCenter.DownWriteValueResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).DownWriteValue(inValue);
            return retVal.Body.DownWriteValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.AddDeviceResponse SocketDemo.CDataCenter.CDataCenterSoap.AddDevice(SocketDemo.CDataCenter.AddDeviceRequest request) {
            return base.Channel.AddDevice(request);
        }
        
        public int AddDevice(SocketDemo.CDataCenter.ArrayOfString tagNames) {
            SocketDemo.CDataCenter.AddDeviceRequest inValue = new SocketDemo.CDataCenter.AddDeviceRequest();
            inValue.Body = new SocketDemo.CDataCenter.AddDeviceRequestBody();
            inValue.Body.tagNames = tagNames;
            SocketDemo.CDataCenter.AddDeviceResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).AddDevice(inValue);
            return retVal.Body.AddDeviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.RemoveDeviceResponse SocketDemo.CDataCenter.CDataCenterSoap.RemoveDevice(SocketDemo.CDataCenter.RemoveDeviceRequest request) {
            return base.Channel.RemoveDevice(request);
        }
        
        public int RemoveDevice(SocketDemo.CDataCenter.ArrayOfString tagName) {
            SocketDemo.CDataCenter.RemoveDeviceRequest inValue = new SocketDemo.CDataCenter.RemoveDeviceRequest();
            inValue.Body = new SocketDemo.CDataCenter.RemoveDeviceRequestBody();
            inValue.Body.tagName = tagName;
            SocketDemo.CDataCenter.RemoveDeviceResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).RemoveDevice(inValue);
            return retVal.Body.RemoveDeviceResult;
        }
        
        public bool Refresh() {
            return base.Channel.Refresh();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.DownGetDeviceInfoResponse SocketDemo.CDataCenter.CDataCenterSoap.DownGetDeviceInfo(SocketDemo.CDataCenter.DownGetDeviceInfoRequest request) {
            return base.Channel.DownGetDeviceInfo(request);
        }
        
        public string DownGetDeviceInfo(string DeviceName) {
            SocketDemo.CDataCenter.DownGetDeviceInfoRequest inValue = new SocketDemo.CDataCenter.DownGetDeviceInfoRequest();
            inValue.Body = new SocketDemo.CDataCenter.DownGetDeviceInfoRequestBody();
            inValue.Body.DeviceName = DeviceName;
            SocketDemo.CDataCenter.DownGetDeviceInfoResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).DownGetDeviceInfo(inValue);
            return retVal.Body.DownGetDeviceInfoResult;
        }
        
        public int testdownwritevaluestring() {
            return base.Channel.testdownwritevaluestring();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SocketDemo.CDataCenter.testupreadvalueResponse SocketDemo.CDataCenter.CDataCenterSoap.testupreadvalue(SocketDemo.CDataCenter.testupreadvalueRequest request) {
            return base.Channel.testupreadvalue(request);
        }
        
        public SocketDemo.CDataCenter.ArrayOfUpDataValue testupreadvalue() {
            SocketDemo.CDataCenter.testupreadvalueRequest inValue = new SocketDemo.CDataCenter.testupreadvalueRequest();
            inValue.Body = new SocketDemo.CDataCenter.testupreadvalueRequestBody();
            SocketDemo.CDataCenter.testupreadvalueResponse retVal = ((SocketDemo.CDataCenter.CDataCenterSoap)(this)).testupreadvalue(inValue);
            return retVal.Body.testupreadvalueResult;
        }
    }
}
